name: Moonchild Grimoire Intake
on:
  push:
    paths:
      - 'circuitum99/art/img/sigils/**'
      - 'circuitum99/main/registry/characters/moonchild/meta_layers/grimoires/**'
  workflow_dispatch:
permissions:
  contents: write
jobs:
  intake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Append intake entries for new files
        run: |
          set -e
          LOG="circuitum99/main/04_registry-meta/system/logs/moonchild/grimoire-intake.md"
          mkdir -p "$(dirname "$LOG")"
          echo "## Intake $(date -u +'%Y-%m-%d %H:%M:%S') UTC" >> "$LOG"

          # List new/modified files from this push within watched paths
          CHANGED="$(git diff --name-only HEAD~1..HEAD -- 'circuitum99/art/img/sigils/**' 'circuitum99/main/registry/characters/moonchild/meta_layers/grimoires/**' || true)"
          if [ -z "$CHANGED" ]; then
            echo "- (no new artifacts)" >> "$LOG"
          else
            while IFS= read -r f; do
              [ -n "$f" ] || continue
              echo "- ${f}" >> "$LOG"
            done <<EOF
$CHANGED
EOF
          fi
          echo "" >> "$LOG"
      - name: Commit (if changed)
        run: |
          set -e
          git config user.name  "moonchild-bot"
          git config user.email "actions@users.noreply.github.com"
          if [ -n "$(git status --porcelain)" ]; then
            git add -A
            git commit -m "intake: grimoire artifacts logged [skip ci]"
            git push
          else
            echo "No changes."
          fi