name: Crucible · Autopilot (safe)

on:
  push:
    branches: ['**']
  schedule:
    - cron: '*/33 * * * *'   # every 33 minutes (UTC)
  workflow_dispatch: {}

permissions:
  contents: read    # default read; we upload artifacts only

jobs:
  drymix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0, lfs: false }

      - name: Install yq
        run: sudo snap install yq

      - name: Build read-only preview (no edits to sources)
        shell: bash
        run: |
          set -euo pipefail
          CFG="main/registry/00_CRUCIBLE/crucible.yml"
          PREVIEW_DIR="$(yq '.output.preview_dir' "$CFG")"
          INDEX_FILE="$(yq '.output.index_file'  "$CFG")"
          SIGILS_DIR="$(yq '.art.sigils_dir'     "$CFG")"
          mkdir -p "$PREVIEW_DIR"

          # header
          {
            echo "# Circuitum 99 · Crucible Preview"
            echo "_Autopilot preview; sources are untouched._"
            echo
            echo "## Sigils"
            if [ -d "$SIGILS_DIR" ]; then
              find "$SIGILS_DIR" -maxdepth 1 -type f -iregex '.*\.\(svg\|png\|jpg\|jpeg\)' -printf "- %f\n" | sort || true
            else
              echo "- (none yet)"
            fi
            echo
            echo "## Chapters (highest layer wins)"
            echo "| Title | Layer | File | Size |"
            echo "|---|---|---|---|"
          } > "$INDEX_FILE"

          # precedence pass
          mapfile -t ORDER < <(yq '.precedence[]' "$CFG")
          declare -A SEEN
          for layer in "${ORDER[@]}"; do
            SRC=$(yq ".inputs.$layer" "$CFG")
            [ -d "$SRC" ] || continue
            while IFS= read -r -d '' f; do
              base="$(basename "$f")"
              key="${base,,}"
              [ -n "${SEEN[$key]:-}" ] && continue
              SEEN[$key]="$layer"
              mkdir -p "$PREVIEW_DIR/$layer"
              cp -n "$f" "$PREVIEW_DIR/$layer/$base" || true
              title="$(grep -m1 -E '^# ' "$f" | sed 's/^# //; s/|/-/g' || echo "$base")"
              wcw="$(wc -w < "$f" | tr -d ' ')"
              echo "| $title | $layer | $base | ${wcw:-0} words |" >> "$INDEX_FILE"
            done < <(find "$SRC" -type f -name "*.md" -print0)
          done

      - name: Upload preview artifact
        uses: actions/upload-artifact@v4
        with:
          name: crucible-preview
          path: main/registry/00_CRUCIBLE/build/preview
          if-no-files-found: warn