name: Moonchild Diagnose (Manual)

on:
  workflow_dispatch: {}

jobs:
  diag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 1, lfs: false }
      - name: Tree + quick scan
        run: |
          (command -v tree >/dev/null || sudo apt-get update && sudo apt-get install -y tree) >/dev/null 2>&1
          echo "### TREE (top 4)"
          tree -a -L 4 -I ".git" || true
          echo
          echo "### FOUND"
          for f in registry.md 00_readme.md moonchild_profile.md moonchild_meta_layers.md activation-log.md dream-log.md system-log.md grimoire-intake.md moonchild_invocation.md purity_filter.md saturns_law.md; do
            find . -type f -iname "$f" | sed "s|^\./||" || true
          done