name: Moonchild Repair

on:
  push:
    paths:
      - "main/registry/**"
      - "scripts/**"
      - "protection/**"
      - "safety/protection/**"
      - "brand/guardrails/**"
      - "wisdom_archive/**"
      - "recovery/**"
      - "docs/**"
      - "book/**"
      - ".gitattributes"
  pull_request:
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (with LFS)
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Setup Git LFS
        run: |
          git lfs install
          git lfs fetch --all || true
          git lfs checkout || true

      - name: Validate Moonchild core (your real paths)
        shell: bash
        run: |
          set -e
          must() { [ -e "$1" ] && echo "✔ $1" || { echo "✘ $1 missing"; exit 1; }; }

          # Registry & node (REAL paths in your repo)
          must main/registry/04_registry-meta/registry.md
          must main/registry/characters/moonchild/00_README.md
          must main/registry/characters/moonchild/moonchild_profile.md
          must main/registry/characters/moonchild/meta_layers/moonchild_meta_layers.md

          # Logs (REAL paths in your repo)
          must main/registry/04_registry-meta/system/logs/moonchild/activation-log.md
          must main/registry/04_registry-meta/system/logs/moonchild/dream-log.md
          must main/registry/04_registry-meta/system/logs/moonchild/system-log.md
          must main/registry/04_registry-meta/system/logs/moonchild/grimoire-intake.md

          # Invocation script (present at repo root/scripts)
          must scripts/moonchild_invocation.md

      - name: Validate protections (allow multiple homes)
        shell: bash
        run: |
          set -e
          must_any() {
            label="$1"; shift
            for p in "$@"; do
              if [ -e "$p" ]; then echo "✔ $label -> $p"; return 0; fi
            done
            echo "✘ $label missing in any of: $*"; exit 1
          }
          must_any "Purity Filter" \
            protection/purity_filter.md \
            safety/protection/purity_filter.md \
            brand/guardrails/purity_filter.md
          must_any "Saturn's Law" \
            protection/saturns_law.md \
            safety/protection/saturns_law.md \
            brand/guardrails/saturns_law.md

      - name: Markdown link sanity (common mistakes)
        shell: bash
        run: |
          set -e
          fails=0
          # Common bad patterns we saw earlier
          grep -RIn "](" --include="*.md" . | grep -E "Moonchild/|moonchild_meta_layers\.md|00_readme\.md" && fails=1 || true
          [ $fails -eq 0 ] || { echo "✘ markdown link pattern check failed (fix casing/filenames)"; exit 1; }

      - name: Emit summary
        shell: bash
        run: |
          echo "### Moonchild Repair Summary" >> $GITHUB_STEP_SUMMARY
          echo "- Core files present ✅" >> $GITHUB_STEP_SUMMARY
          echo "- Protections resolved across multiple locations ✅" >> $GITHUB_STEP_SUMMARY
          echo "- Markdown link sanity passed ✅ (or fix flagged lines)" >> $GITHUB_STEP_SUMMARY