name: Moonchild → Call Autodetect

on:
  workflow_dispatch: {}
  push:
    branches: ['**']

permissions:
  contents: write
  pull-requests: write

jobs:
  autodetect:
    uses: ./.github/workflows/_moonchild_autodetect_reusable.yml

  log_snapshot:
    needs: [autodetect]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0, lfs: false }

      - name: Append detection snapshot to heartbeat.md
        env:
          REGISTRY:  ${{ needs.autodetect.outputs.REGISTRY }}
          READ_ME:   ${{ needs.autodetect.outputs.READ_ME }}
          PROFILE:   ${{ needs.autodetect.outputs.PROFILE }}
          META:      ${{ needs.autodetect.outputs.META }}
        shell: bash
        run: |
          set -euo pipefail
          LOG_DIR="main/registry/04_registry-meta/system/logs/moonchild"
          mkdir -p "$LOG_DIR"
          TS="$(date -u +'%Y-%m-%d %H:%M UTC')"
          {
            echo "## Autodetect snapshot $TS"
            echo "- Registry:   ${REGISTRY:-MISSING}"
            echo "- 00_README:  ${READ_ME:-MISSING}"
            echo "- Profile:    ${PROFILE:-MISSING}"
            echo "- Meta:       ${META:-MISSING}"
            echo
          } >> "$LOG_DIR/heartbeat.md"

      - name: Commit or PR
        id: commit
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name  "moonchild-bot"
            git config user.email "actions@users.noreply.github.com"
            git add -A
            git commit -m "autodetect: snapshot → heartbeat [skip ci]"
            echo "committed=1" >> $GITHUB_OUTPUT
          else
            echo "committed=0" >> $GITHUB_OUTPUT
          fi

      - name: Push
        if: steps.commit.outputs.committed == '1'
        continue-on-error: true
        run: git push

      - name: PR fallback (if branch protected)
        if: steps.commit.outputs.committed == '1'
        uses: peter-evans/create-pull-request@v6
        with:
          branch: bot/autodetect-snapshot-${{ github.run_id }}
          title: "Moonchild autodetect → heartbeat"
          body: "Direct push blocked; opening PR with snapshot."
          commit-message: "autodetect: snapshot → heartbeat"