    name: Moonchild Call Autodetect
on:
  workflow_dispatch:
  push:
    paths:
      - circuitum99/main/04_registry-meta/registry.md
      - circuitum99/main/registry/**
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "workflow parsed and ran"