          - name: Stage ONLY Moonchild files
        id: stage
        shell: bash
        run: |
          set -euo pipefail
          echo "---- git status (pre-stage) ----"
          git status --porcelain

          # Unstage anything that might already be staged
          git restore --staged :/ || true

          # Whitelist the ONLY paths this bot is allowed to touch
          ALLOW=(
            "main/registry/04_registry-meta/system/logs/moonchild"                     # heartbeat + grimoire-intake.md
            "main/registry/characters/moonchild/meta_layers/grimoires/index.yml"       # grimoire index
            "circuitum99/art/img/sigils"                                               # your real sigil folder
          )

          for p in "${ALLOW[@]}"; do
            [ -e "$p" ] && git add "$p" || true
          done

          echo "---- git status (post-stage) ----"
          git status --porcelain

          # Safety: if anything outside the whitelist is staged, abort
          if git diff --name-only --cached | grep -Ev '^(main/registry/04_registry-meta/system/logs/moonchild|main/registry/characters/moonchild/meta_layers/grimoires/index.yml|circuitum99/art/img/sigils)($|/)' ; then
            echo "::error::Detected staged changes outside allowed paths. Aborting commit."
            exit 1
          fi

          # Flag whether we have anything to commit
          if [ -n "$(git diff --cached --name-only)" ]; then
            echo "staged=1" >> $GITHUB_OUTPUT
          else
            echo "staged=0" >> $GITHUB_OUTPUT
          fi